### ISSUE TITLE
Plugins13 Hyper-V Integration Components Version.ps1

### ISSUE THREAD

**Issue by ghost** [vCheckReport/vCheck-SCVMM#2]
The only error I am getting running the script against SC VMM is below. Will appreciate any help to fix this please.

Missing expression after unary operator ‘-’.
At C:\vCheck\Plugins13 Hyper-V Integration Components Version.ps1:83 char:3
- – <<<< Query "SELECT \* FROM Msvm_ComputerSystem WHERE EnabledState=2 AND NOT Caption LIKE 'Hosting Computer System'"
- CategoryInfo : ParserError: (-:String) [], ParseException
- FullyQualifiedErrorId : MissingExpressionAfterOperator

**Comment by Sneddo** [comment]
Closing, issue is too old...
