### ISSUE TITLE
Could we have an update for 2012R2?

### ISSUE THREAD

**Issue by Hangs89** [vCheckReport/vCheck-SCVMM#4]
Great script, would it be possible to have an update to the integration services plugin so that it works with Hyper-V/SCVMM 2012R2? Thanks.

**Comment by mrclschstr** [comment]
+1

**Comment by jkavanagh58** [comment]
+1

**Comment by Totorman** [comment]
for me to run correctly on scvmm2012 r2 on hyperV r3 hosts :
- had to configure the GlobalVariables.ps1 manually (easy to do)
- had to modify the 013th plugin : there whas a glitch (utf to iso conversion ?) on first line making the $title variable line not recognized by powershell
- had to modify the 013th plugin : changed root\virtualization to root\virtualization\v2
- had to modify the 013th plugin : put the whole wmi requests into a single line

After that the script ran fine and i was able to get my html report.

**Comment by AlphaCasper2001** [comment]
per Totman's comments - i had to do the same.  I also ran into an issue where we were using 2012 and 2012 R2 versions of hyper-v.  To avoid getting the error, I put in a get-SCVMHost version information. 

The following changes were made:

After the following lines:

    ```
     $hostSession = new-pssession -computername $hostname

    $icVersionParent = invoke-command -session $hostSession -scriptblock {Get-ChildItem "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\GuestInstaller" | ForEach-Object {Get-ItemProperty $_.pspath} | select-object "Microsoft-Hyper-V-Guest-Installer"}


```

Insert the following lines:

    ```
IF ((Get-SCVMHost -ComputerName $hostName).hypervversion -eq "6.1.7601.17514") {
          $guests = Get-WmiObject -Namespace root\virtualization -ComputerName $hostName -Query "SELECT * FROM Msvm_ComputerSystem WHERE EnabledState=2 AND NOT Caption LIKE 'Hosting Computer System'"
         }

 IF ((Get-SCVMHost -ComputerName $hostName).hypervversion -like "6.2.*") {
         $guests = Get-WmiObject -Namespace root\virtualization\v2 -ComputerName $hostName -Query "SELECT * FROM Msvm_ComputerSystem WHERE EnabledState=2 AND NOT Caption LIKE 'Hosting Computer System'"
       }

 IF ((Get-SCVMHost -ComputerName $hostName).hypervversion -like "6.3.*") {
          $guests = Get-WmiObject -Namespace root\virtualization\v2 -ComputerName $hostName -Query "SELECT * FROM Msvm_ComputerSystem WHERE EnabledState=2 AND NOT Caption LIKE 'Hosting Computer System'"
      }

```

Hopes this helps!
attached the file as well (just rename)
- anyone figure out how to add multilpe emails?

Jess


[013 Hyper-V Integration Components Version.ps1.txt](https://github.com/alanrenouf/vCheck-SCVMM/files/221695/013.Hyper-V.Integration.Components.Version.ps1.txt)

**Comment by Hangs89** [comment]
Thanks for your replies! Plugin 13 was what I was having problems with also. I was able to amend the other scripts OK. I will make the ammendments when back at work.

**Comment by Sneddo** [comment]
Commited these changes, hopefully it works... 🤞
